name: ${project.name}
version: ${project.version}
main: com.kennedysmithjava.prisoncore.PrisonCore
api-version: 1.18
authors: [ "KennedySmithJava" ]
description: its a plugin
website: MCRivals.com
depend: [Citizens, MassiveCore, FastAsyncWorldEdit, ProtocolLib, HolographicDisplays, ProtocolLib, WorldGuard, PlaceholderAPI]