name: ${project.name}
version: ${project.version}
main: com.kennedysmithjava.prisonmines.PrisonMines
api-version: 1.8
authors: [ "KennedySmithJava", "Hadimhz" ]
description: PP
website: MCRivals.com
depend: [MassiveCore]
