package com.kennedysmithjava.prisonmines.util;

public enum UpgradeName {

        /* Upgrade Categories */
        CATEGORY_BUILDINGS,
        CATEGORY_ARCHITECTURE,
        CATEGORY_REGENERATION,
        CATEGORY_STORAGE,
        CATEGORY_MOBILITY,
        CATEGORY_AUTOMATION,
        CATEGORY_COLLECTION,

        /* BUILDINGS */
        BUILDING_PORTAL,
        BUILDING_ENCHANT_TABLE,
        BUILDING_TRASH_CAN,
        BUILDING_ANVIL,
        BUILDING_BEACON,

        /* ARCHITECTURE */
        ARCHITECTURE_HEIGHT_INCREASE,
        ARCHITECTURE_HEIGHT_DECREASE,
        ARCHITECTURE_WIDTH_INCREASE,
        ARCHITECTURE_WIDTH_DECREASE,
        ARCHITECTURE_PATHS,
        ARCHITECTURE_WALLS,

        /* REGENERATION */
        REGENERATION_MANUAL,
        REGENERATION_MANUAL_ANIMATION_OPEN_1,
        REGENERATION_MANUAL_ANIMATION_OPEN_2,
        REGENERATION_MANUAL_ANIMATION_OPEN_3,
        REGENERATION_MANUAL_ANIMATION_OPEN_4,
        REGENERATION_MANUAL_ANIMATION_OPEN_5,
        REGENERATION_MANUAL_ANIMATION_OPEN_6,
        REGENERATION_MANUAL_ANIMATION_OPEN_7,
        REGENERATION_MANUAL_ANIMATION_CLOSE_1,
        REGENERATION_MANUAL_ANIMATION_CLOSE_2,
        REGENERATION_MANUAL_ANIMATION_CLOSE_3,
        REGENERATION_MANUAL_ANIMATION_CLOSE_4,
        REGENERATION_MANUAL_ANIMATION_CLOSE_5,
        REGENERATION_MANUAL_ANIMATION_CLOSE_6,
        REGENERATION_MANUAL_ANIMATION_CLOSE_7,
        REGENERATION_MANUAL_ANIMATION_DELAY_1,
        REGENERATION_MANUAL_ANIMATION_DELAY_2,
        REGENERATION_MANUAL_ANIMATION_DELAY_3,
        REGENERATION_MANUAL_ANIMATION_DELAY_4,
        REGENERATION_MANUAL_ANIMATION_DELAY_5,
        REGENERATION_MANUAL_ANIMATION_DELAY_6,
        REGENERATION_MANUAL_ANIMATION_DELAY_7,
        REGENERATION_AUTO,
        REGENERATION_AUTO_SPEED_1,
        REGENERATION_AUTO_SPEED_2,
        REGENERATION_AUTO_SPEED_3,
        REGENERATION_AUTO_SPEED_4,
        REGENERATION_AUTO_SPEED_5,
        REGENERATION_AUTO_SPEED_6,
        REGENERATION_AUTO_SPEED_7,

        /* STORAGE */
        CHEST,
        CHEST_SIZE_HOPPER,
        CHEST_SIZE_DROPPER,
        CHEST_SIZE_SINGLE,
        CHEST_SIZE_DOUBLE,
        CHEST_SIZE_DOUBLE_2,
        CHEST_SIZE_DOUBLE_4,
        CHEST_SIZE_DOUBLE_5,
        CHEST_COMMAND,

        /* Mobility */
        MOBILITY_LADDER_1,
        MOBILITY_LADDER_2,
        MOBILITY_LADDER_3,
        MOBILITY_JUMP_PAD,
        FLIGHT

        /* COLLECTION */
        ;

        public String get(){
            return this.name();
        }

    }
