package com.kennedysmithjava.prisoncore.entity.mines.upgrades;

public enum UpgradeName {

    /* Upgrade Categories */
    CATEGORY_BUILDINGS,
    CATEGORY_ARCHITECTURE,
    CATEGORY_REGENERATION,
    CATEGORY_FAST_TRAVEL,
    CATEGORY_MOBILITY,
    CATEGORY_ROBOTICS,
    CATEGORY_COLLECTION,
    CATEGORY_ENVIRONMENT,

    /* BUILDINGS */
    BUILDING_PORTAL,
    BUILDING_ENCHANT_TABLE,
    BUILDING_ANVIL,
    BUILDING_BEACON,
    BUILDING_STORAGE,

    /* ARCHITECTURE */
    ARCHITECTURE_HEIGHT_INCREASE,
    ARCHITECTURE_HEIGHT_DECREASE,
    ARCHITECTURE_WIDTH_INCREASE,
    ARCHITECTURE_WIDTH_DECREASE,
    ARCHITECTURE_PATHS,
    ARCHITECTURE_WALLS,

    /* REGENERATION */
    REGENERATION_MANUAL,
    REGENERATION_MANUAL_ANIMATION_SPEED_1,
    REGENERATION_MANUAL_ANIMATION_SPEED_2,
    REGENERATION_MANUAL_ANIMATION_SPEED_3,
    REGENERATION_MANUAL_ANIMATION_SPEED_4,
    REGENERATION_MANUAL_ANIMATION_SPEED_5,
    REGENERATION_MANUAL_ANIMATION_SPEED_6,
    REGENERATION_MANUAL_ANIMATION_SPEED_7,
    REGENERATION_MANUAL_ANIMATION_DELAY_1,
    REGENERATION_MANUAL_ANIMATION_DELAY_2,
    REGENERATION_MANUAL_ANIMATION_DELAY_3,
    REGENERATION_MANUAL_ANIMATION_DELAY_4,
    REGENERATION_MANUAL_ANIMATION_DELAY_5,
    REGENERATION_MANUAL_ANIMATION_DELAY_6,
    REGENERATION_MANUAL_ANIMATION_DELAY_7,
    REGENERATION_AUTO,
    REGENERATION_AUTO_SPEED_1,
    REGENERATION_AUTO_SPEED_2,
    REGENERATION_AUTO_SPEED_3,
    REGENERATION_AUTO_SPEED_4,
    REGENERATION_AUTO_SPEED_5,
    REGENERATION_AUTO_SPEED_6,
    REGENERATION_AUTO_SPEED_7,

    /* Mobility */
    MOBILITY_LADDER_1,
    MOBILITY_LADDER_2,
    MOBILITY_LADDER_3,
    MOBILITY_JUMP_PAD,
    MOBILITY_FLIGHT,

    /* COLLECTION */
    COLLECTION_DEFAULT,
    COLLECTION_SELECT_ALL,
    COLLECTION_SELL_ALL,
    COLLECTION_AUTO_1,
    COLLECTION_AUTO_2,
    COLLECTION_AUTO_3,
    COLLECTION_AUTO_4

    ;

    public String get(){
        return this.name();
    }

}
