name: PrisonMines
version: 1.0
main: com.kennedysmithjava.prisonmines.PrisonMines
api-version: 1.8
authors: [ "KennedySmithJava" ]
description: PP
website: MCRivals.com
depend: [MassiveCore, FastAsyncWorldEdit, Citizens]
softdepend: [PrisonCore]
loadbefore: [PrisonCore]
